//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.08 at 04:20:04 PM EST 
//


package com.econdates.xignite.xsd.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CountryCodes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CountryCodes">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xignite.com/services/}AbstractEconodayObject">
 *       &lt;sequence>
 *         &lt;element name="CountryCodes" type="{http://www.xignite.com/services/}ArrayOfCountryCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CountryCodes", propOrder = {
    "countryCodes"
})
public class CountryCodes
    extends AbstractEconodayObject
{

    @XmlElement(name = "CountryCodes")
    protected ArrayOfCountryCode countryCodes;

    /**
     * Gets the value of the countryCodes property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCountryCode }
     *     
     */
    public ArrayOfCountryCode getCountryCodes() {
        return countryCodes;
    }

    /**
     * Sets the value of the countryCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCountryCode }
     *     
     */
    public void setCountryCodes(ArrayOfCountryCode value) {
        this.countryCodes = value;
    }

}
