//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.08 at 04:20:04 PM EST 
//


package com.econdates.xignite.xsd.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EventDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventDetails">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xignite.com/services/}AbstractEconodayObject">
 *       &lt;sequence>
 *         &lt;element name="EventID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EventCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EventName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReleasedOn" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Values" type="{http://www.xignite.com/services/}ArrayOfEventValue" minOccurs="0"/>
 *         &lt;element name="Definition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsInternational" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ReleasedFor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReleasedForStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ReleasedForEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventDetails", propOrder = {
    "eventID",
    "eventCode",
    "countryCode",
    "eventName",
    "releasedOn",
    "values",
    "definition",
    "description",
    "countryName",
    "isInternational",
    "releasedFor",
    "releasedForStart",
    "releasedForEnd"
})
public class EventDetails
    extends AbstractEconodayObject
{

    @XmlElement(name = "EventID")
    protected String eventID;
    @XmlElement(name = "EventCode")
    protected String eventCode;
    @XmlElement(name = "CountryCode")
    protected String countryCode;
    @XmlElement(name = "EventName")
    protected String eventName;
    @XmlElement(name = "ReleasedOn", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar releasedOn;
    @XmlElement(name = "Values")
    protected ArrayOfEventValue values;
    @XmlElement(name = "Definition")
    protected String definition;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "CountryName")
    protected String countryName;
    @XmlElement(name = "IsInternational")
    protected boolean isInternational;
    @XmlElement(name = "ReleasedFor")
    protected String releasedFor;
    @XmlElement(name = "ReleasedForStart", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar releasedForStart;
    @XmlElement(name = "ReleasedForEnd", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar releasedForEnd;

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventID(String value) {
        this.eventID = value;
    }

    /**
     * Gets the value of the eventCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventCode() {
        return eventCode;
    }

    /**
     * Sets the value of the eventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventCode(String value) {
        this.eventCode = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the eventName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * Sets the value of the eventName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventName(String value) {
        this.eventName = value;
    }

    /**
     * Gets the value of the releasedOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReleasedOn() {
        return releasedOn;
    }

    /**
     * Sets the value of the releasedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReleasedOn(XMLGregorianCalendar value) {
        this.releasedOn = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfEventValue }
     *     
     */
    public ArrayOfEventValue getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfEventValue }
     *     
     */
    public void setValues(ArrayOfEventValue value) {
        this.values = value;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinition(String value) {
        this.definition = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the countryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the value of the countryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryName(String value) {
        this.countryName = value;
    }

    /**
     * Gets the value of the isInternational property.
     * 
     */
    public boolean isIsInternational() {
        return isInternational;
    }

    /**
     * Sets the value of the isInternational property.
     * 
     */
    public void setIsInternational(boolean value) {
        this.isInternational = value;
    }

    /**
     * Gets the value of the releasedFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleasedFor() {
        return releasedFor;
    }

    /**
     * Sets the value of the releasedFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleasedFor(String value) {
        this.releasedFor = value;
    }

    /**
     * Gets the value of the releasedForStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReleasedForStart() {
        return releasedForStart;
    }

    /**
     * Sets the value of the releasedForStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReleasedForStart(XMLGregorianCalendar value) {
        this.releasedForStart = value;
    }

    /**
     * Gets the value of the releasedForEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReleasedForEnd() {
        return releasedForEnd;
    }

    /**
     * Sets the value of the releasedForEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReleasedForEnd(XMLGregorianCalendar value) {
        this.releasedForEnd = value;
    }

}
