//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.08 at 04:20:04 PM EST 
//


package com.econdates.xignite.xsd.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventSummaries complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventSummaries">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xignite.com/services/}AbstractEconodayObject">
 *       &lt;sequence>
 *         &lt;element name="Summaries" type="{http://www.xignite.com/services/}ArrayOfEventSummary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventSummaries", propOrder = {
    "summaries"
})
public class EventSummaries
    extends AbstractEconodayObject
{

    @XmlElement(name = "Summaries")
    protected ArrayOfEventSummary summaries;

    /**
     * Gets the value of the summaries property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfEventSummary }
     *     
     */
    public ArrayOfEventSummary getSummaries() {
        return summaries;
    }

    /**
     * Sets the value of the summaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfEventSummary }
     *     
     */
    public void setSummaries(ArrayOfEventSummary value) {
        this.summaries = value;
    }

}
