//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.08 at 04:20:04 PM EST 
//


package com.econdates.xignite.xsd.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.econdates.xignite.xsd.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EventSummaries_QNAME = new QName("http://www.xignite.com/services/", "EventSummaries");
    private final static QName _MultipleEventDetails_QNAME = new QName("http://www.xignite.com/services/", "MultipleEventDetails");
    private final static QName _EventDetails_QNAME = new QName("http://www.xignite.com/services/", "EventDetails");
    private final static QName _Header_QNAME = new QName("http://www.xignite.com/services/", "Header");
    private final static QName _EventCodes_QNAME = new QName("http://www.xignite.com/services/", "EventCodes");
    private final static QName _CountryCodes_QNAME = new QName("http://www.xignite.com/services/", "CountryCodes");
    private final static QName _DocumentationResult_QNAME = new QName("http://www.xignite.com/services/", "DocumentationResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.econdates.xignite.xsd.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetEventsByEventCode }
     * 
     */
    public GetEventsByEventCode createGetEventsByEventCode() {
        return new GetEventsByEventCode();
    }

    /**
     * Create an instance of {@link CountryCode }
     * 
     */
    public CountryCode createCountryCode() {
        return new CountryCode();
    }

    /**
     * Create an instance of {@link GetEventsForWeekResponse }
     * 
     */
    public GetEventsForWeekResponse createGetEventsForWeekResponse() {
        return new GetEventsForWeekResponse();
    }

    /**
     * Create an instance of {@link GetEventsForTomorrowResponse }
     * 
     */
    public GetEventsForTomorrowResponse createGetEventsForTomorrowResponse() {
        return new GetEventsForTomorrowResponse();
    }

    /**
     * Create an instance of {@link EventSummary }
     * 
     */
    public EventSummary createEventSummary() {
        return new EventSummary();
    }

    /**
     * Create an instance of {@link GetEventsForDateResponse }
     * 
     */
    public GetEventsForDateResponse createGetEventsForDateResponse() {
        return new GetEventsForDateResponse();
    }

    /**
     * Create an instance of {@link GetEventsReleasedForRangeResponse }
     * 
     */
    public GetEventsReleasedForRangeResponse createGetEventsReleasedForRangeResponse() {
        return new GetEventsReleasedForRangeResponse();
    }

    /**
     * Create an instance of {@link GetEventsByEventNameResponse }
     * 
     */
    public GetEventsByEventNameResponse createGetEventsByEventNameResponse() {
        return new GetEventsByEventNameResponse();
    }

    /**
     * Create an instance of {@link GetEventsForRangeLengthResponse }
     * 
     */
    public GetEventsForRangeLengthResponse createGetEventsForRangeLengthResponse() {
        return new GetEventsForRangeLengthResponse();
    }

    /**
     * Create an instance of {@link GetMostRecentEventsByEventCodeResponse }
     * 
     */
    public GetMostRecentEventsByEventCodeResponse createGetMostRecentEventsByEventCodeResponse() {
        return new GetMostRecentEventsByEventCodeResponse();
    }

    /**
     * Create an instance of {@link GetEventsReleasedForRange }
     * 
     */
    public GetEventsReleasedForRange createGetEventsReleasedForRange() {
        return new GetEventsReleasedForRange();
    }

    /**
     * Create an instance of {@link GetEventsByCountryCodeResponse }
     * 
     */
    public GetEventsByCountryCodeResponse createGetEventsByCountryCodeResponse() {
        return new GetEventsByCountryCodeResponse();
    }

    /**
     * Create an instance of {@link GetEventsForTomorrow }
     * 
     */
    public GetEventsForTomorrow createGetEventsForTomorrow() {
        return new GetEventsForTomorrow();
    }

    /**
     * Create an instance of {@link GetServiceDemonstrationResponse }
     * 
     */
    public GetServiceDemonstrationResponse createGetServiceDemonstrationResponse() {
        return new GetServiceDemonstrationResponse();
    }

    /**
     * Create an instance of {@link GetEventsForMonth }
     * 
     */
    public GetEventsForMonth createGetEventsForMonth() {
        return new GetEventsForMonth();
    }

    /**
     * Create an instance of {@link ArrayOfEventDetails }
     * 
     */
    public ArrayOfEventDetails createArrayOfEventDetails() {
        return new ArrayOfEventDetails();
    }

    /**
     * Create an instance of {@link GetEventDetails }
     * 
     */
    public GetEventDetails createGetEventDetails() {
        return new GetEventDetails();
    }

    /**
     * Create an instance of {@link GetEventsByEventCodeResponse }
     * 
     */
    public GetEventsByEventCodeResponse createGetEventsByEventCodeResponse() {
        return new GetEventsByEventCodeResponse();
    }

    /**
     * Create an instance of {@link ListCountryCodesResponse }
     * 
     */
    public ListCountryCodesResponse createListCountryCodesResponse() {
        return new ListCountryCodesResponse();
    }

    /**
     * Create an instance of {@link GetEventsReleasedForRangeLengthResponse }
     * 
     */
    public GetEventsReleasedForRangeLengthResponse createGetEventsReleasedForRangeLengthResponse() {
        return new GetEventsReleasedForRangeLengthResponse();
    }

    /**
     * Create an instance of {@link ArrayOfCountryCode }
     * 
     */
    public ArrayOfCountryCode createArrayOfCountryCode() {
        return new ArrayOfCountryCode();
    }

    /**
     * Create an instance of {@link GetEventDetailsResponse }
     * 
     */
    public GetEventDetailsResponse createGetEventDetailsResponse() {
        return new GetEventDetailsResponse();
    }

    /**
     * Create an instance of {@link EventDetails }
     * 
     */
    public EventDetails createEventDetails() {
        return new EventDetails();
    }

    /**
     * Create an instance of {@link GetServiceDemonstration }
     * 
     */
    public GetServiceDemonstration createGetServiceDemonstration() {
        return new GetServiceDemonstration();
    }

    /**
     * Create an instance of {@link ArrayOfEventCode }
     * 
     */
    public ArrayOfEventCode createArrayOfEventCode() {
        return new ArrayOfEventCode();
    }

    /**
     * Create an instance of {@link GetEventsForRangeResponse }
     * 
     */
    public GetEventsForRangeResponse createGetEventsForRangeResponse() {
        return new GetEventsForRangeResponse();
    }

    /**
     * Create an instance of {@link GetEventsReleasedForRangeLength }
     * 
     */
    public GetEventsReleasedForRangeLength createGetEventsReleasedForRangeLength() {
        return new GetEventsReleasedForRangeLength();
    }

    /**
     * Create an instance of {@link Common }
     * 
     */
    public Common createCommon() {
        return new Common();
    }

    /**
     * Create an instance of {@link EventValue }
     * 
     */
    public EventValue createEventValue() {
        return new EventValue();
    }

    /**
     * Create an instance of {@link GetEventsForNextNumberOfDaysResponse }
     * 
     */
    public GetEventsForNextNumberOfDaysResponse createGetEventsForNextNumberOfDaysResponse() {
        return new GetEventsForNextNumberOfDaysResponse();
    }

    /**
     * Create an instance of {@link EventCode }
     * 
     */
    public EventCode createEventCode() {
        return new EventCode();
    }

    /**
     * Create an instance of {@link ArrayOfEventValue }
     * 
     */
    public ArrayOfEventValue createArrayOfEventValue() {
        return new ArrayOfEventValue();
    }

    /**
     * Create an instance of {@link EventCodes }
     * 
     */
    public EventCodes createEventCodes() {
        return new EventCodes();
    }

    /**
     * Create an instance of {@link SearchEventsResponse }
     * 
     */
    public SearchEventsResponse createSearchEventsResponse() {
        return new SearchEventsResponse();
    }

    /**
     * Create an instance of {@link GetMultipleEventDetails }
     * 
     */
    public GetMultipleEventDetails createGetMultipleEventDetails() {
        return new GetMultipleEventDetails();
    }

    /**
     * Create an instance of {@link ListCountryCodes }
     * 
     */
    public ListCountryCodes createListCountryCodes() {
        return new ListCountryCodes();
    }

    /**
     * Create an instance of {@link GetEventsForMonthResponse }
     * 
     */
    public GetEventsForMonthResponse createGetEventsForMonthResponse() {
        return new GetEventsForMonthResponse();
    }

    /**
     * Create an instance of {@link GetMostRecentEventsByEventCode }
     * 
     */
    public GetMostRecentEventsByEventCode createGetMostRecentEventsByEventCode() {
        return new GetMostRecentEventsByEventCode();
    }

    /**
     * Create an instance of {@link ListEventCodes }
     * 
     */
    public ListEventCodes createListEventCodes() {
        return new ListEventCodes();
    }

    /**
     * Create an instance of {@link MultipleEventDetails }
     * 
     */
    public MultipleEventDetails createMultipleEventDetails() {
        return new MultipleEventDetails();
    }

    /**
     * Create an instance of {@link GetEventsForTodayResponse }
     * 
     */
    public GetEventsForTodayResponse createGetEventsForTodayResponse() {
        return new GetEventsForTodayResponse();
    }

    /**
     * Create an instance of {@link GetEventsByEventName }
     * 
     */
    public GetEventsByEventName createGetEventsByEventName() {
        return new GetEventsByEventName();
    }

    /**
     * Create an instance of {@link CountryCodes }
     * 
     */
    public CountryCodes createCountryCodes() {
        return new CountryCodes();
    }

    /**
     * Create an instance of {@link GetEventsByCountryCode }
     * 
     */
    public GetEventsByCountryCode createGetEventsByCountryCode() {
        return new GetEventsByCountryCode();
    }

    /**
     * Create an instance of {@link GetEventsForDate }
     * 
     */
    public GetEventsForDate createGetEventsForDate() {
        return new GetEventsForDate();
    }

    /**
     * Create an instance of {@link DocumentationResult }
     * 
     */
    public DocumentationResult createDocumentationResult() {
        return new DocumentationResult();
    }

    /**
     * Create an instance of {@link GetMultipleEventDetailsResponse }
     * 
     */
    public GetMultipleEventDetailsResponse createGetMultipleEventDetailsResponse() {
        return new GetMultipleEventDetailsResponse();
    }

    /**
     * Create an instance of {@link GetEventsForToday }
     * 
     */
    public GetEventsForToday createGetEventsForToday() {
        return new GetEventsForToday();
    }

    /**
     * Create an instance of {@link ArrayOfEventSummary }
     * 
     */
    public ArrayOfEventSummary createArrayOfEventSummary() {
        return new ArrayOfEventSummary();
    }

    /**
     * Create an instance of {@link GetEventsForRange }
     * 
     */
    public GetEventsForRange createGetEventsForRange() {
        return new GetEventsForRange();
    }

    /**
     * Create an instance of {@link SearchEvents }
     * 
     */
    public SearchEvents createSearchEvents() {
        return new SearchEvents();
    }

    /**
     * Create an instance of {@link GetEventsForRangeLength }
     * 
     */
    public GetEventsForRangeLength createGetEventsForRangeLength() {
        return new GetEventsForRangeLength();
    }

    /**
     * Create an instance of {@link EventSummaries }
     * 
     */
    public EventSummaries createEventSummaries() {
        return new EventSummaries();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link GetEventsForNextNumberOfDays }
     * 
     */
    public GetEventsForNextNumberOfDays createGetEventsForNextNumberOfDays() {
        return new GetEventsForNextNumberOfDays();
    }

    /**
     * Create an instance of {@link GetEventsForWeek }
     * 
     */
    public GetEventsForWeek createGetEventsForWeek() {
        return new GetEventsForWeek();
    }

    /**
     * Create an instance of {@link ListEventCodesResponse }
     * 
     */
    public ListEventCodesResponse createListEventCodesResponse() {
        return new ListEventCodesResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventSummaries }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "EventSummaries")
    public JAXBElement<EventSummaries> createEventSummaries(EventSummaries value) {
        return new JAXBElement<EventSummaries>(_EventSummaries_QNAME, EventSummaries.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultipleEventDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "MultipleEventDetails")
    public JAXBElement<MultipleEventDetails> createMultipleEventDetails(MultipleEventDetails value) {
        return new JAXBElement<MultipleEventDetails>(_MultipleEventDetails_QNAME, MultipleEventDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "EventDetails")
    public JAXBElement<EventDetails> createEventDetails(EventDetails value) {
        return new JAXBElement<EventDetails>(_EventDetails_QNAME, EventDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Header }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "Header")
    public JAXBElement<Header> createHeader(Header value) {
        return new JAXBElement<Header>(_Header_QNAME, Header.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventCodes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "EventCodes")
    public JAXBElement<EventCodes> createEventCodes(EventCodes value) {
        return new JAXBElement<EventCodes>(_EventCodes_QNAME, EventCodes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountryCodes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "CountryCodes")
    public JAXBElement<CountryCodes> createCountryCodes(CountryCodes value) {
        return new JAXBElement<CountryCodes>(_CountryCodes_QNAME, CountryCodes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentationResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "DocumentationResult")
    public JAXBElement<DocumentationResult> createDocumentationResult(DocumentationResult value) {
        return new JAXBElement<DocumentationResult>(_DocumentationResult_QNAME, DocumentationResult.class, null, value);
    }

}
