//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.08 at 04:20:04 PM EST 
//


package com.econdates.xignite.xsd.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EventName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EventCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReleasedForStart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReleasedForEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReleasedOnStart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReleasedOnEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GetUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GetInternational" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventName",
    "eventCode",
    "countryCode",
    "releasedForStart",
    "releasedForEnd",
    "releasedOnStart",
    "releasedOnEnd",
    "getUS",
    "getInternational"
})
@XmlRootElement(name = "SearchEvents")
public class SearchEvents {

    @XmlElement(name = "EventName")
    protected String eventName;
    @XmlElement(name = "EventCode")
    protected String eventCode;
    @XmlElement(name = "CountryCode")
    protected String countryCode;
    @XmlElement(name = "ReleasedForStart")
    protected String releasedForStart;
    @XmlElement(name = "ReleasedForEnd")
    protected String releasedForEnd;
    @XmlElement(name = "ReleasedOnStart")
    protected String releasedOnStart;
    @XmlElement(name = "ReleasedOnEnd")
    protected String releasedOnEnd;
    @XmlElement(name = "GetUS")
    protected String getUS;
    @XmlElement(name = "GetInternational")
    protected String getInternational;

    /**
     * Gets the value of the eventName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * Sets the value of the eventName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventName(String value) {
        this.eventName = value;
    }

    /**
     * Gets the value of the eventCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventCode() {
        return eventCode;
    }

    /**
     * Sets the value of the eventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventCode(String value) {
        this.eventCode = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the releasedForStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleasedForStart() {
        return releasedForStart;
    }

    /**
     * Sets the value of the releasedForStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleasedForStart(String value) {
        this.releasedForStart = value;
    }

    /**
     * Gets the value of the releasedForEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleasedForEnd() {
        return releasedForEnd;
    }

    /**
     * Sets the value of the releasedForEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleasedForEnd(String value) {
        this.releasedForEnd = value;
    }

    /**
     * Gets the value of the releasedOnStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleasedOnStart() {
        return releasedOnStart;
    }

    /**
     * Sets the value of the releasedOnStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleasedOnStart(String value) {
        this.releasedOnStart = value;
    }

    /**
     * Gets the value of the releasedOnEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleasedOnEnd() {
        return releasedOnEnd;
    }

    /**
     * Sets the value of the releasedOnEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleasedOnEnd(String value) {
        this.releasedOnEnd = value;
    }

    /**
     * Gets the value of the getUS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetUS() {
        return getUS;
    }

    /**
     * Sets the value of the getUS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetUS(String value) {
        this.getUS = value;
    }

    /**
     * Gets the value of the getInternational property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetInternational() {
        return getInternational;
    }

    /**
     * Sets the value of the getInternational property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetInternational(String value) {
        this.getInternational = value;
    }

}
